### ISSUE TITLE
Got error when try run script

### ISSUE THREAD

**Issue by yahoopl** [karaktaka/grafana-netatmo#11]
chmod on files are 777

root@Grafana:/usr/local/bin# python3 netatmo_influx.py 
Traceback (most recent call last):
  File "/usr/local/bin/netatmo_influx.py", line 151, in <module>
    logger = set_logging_level(args.verbosity, loglevel)
  File "/usr/local/bin/netatmo_influx.py", line 73, in set_logging_level
    pyatmo.helpers.LOG.setLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 1417, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 197, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)
TypeError: Level not an integer or a valid string: None

**Comment by karaktaka** [comment]
Hey, sorry for the late reply.
You need to add  a Loglevel either as environment variable or as config var.

I fixed the docs as it seems i forgot to add it there.
